### ISSUE TITLE
Reply number is assumed for Dutch return labels

### ISSUE THREAD

**Issue by stijneikelboom** [Progressus-io/postnl-for-woocommerce#157]
The plugin assumes that Dutch return labels always have a reply number (_Antwoordnummer_) as the address, which is an option but certainly not always the case. 

First of all, the `return_address` and `return_address_no` are currently only displayed for Belgian addresses.

We have temporarily solved this by commenting out the `for_country` and `class` keys on lines `191-192` and `200-201` in `src/Shipping_Method/Settings.php`.
https://github.com/Progressus-io/postnl-for-woocommerce/blob/eb113a212b9e514c5580057f448975c8191903e2/src/Shipping_Method/Settings.php#L185-L202

Second, upon creating the return label, the `sanitize` function currently always sets `return_address_1` to 'Antwoordnummer', and `return_address_2` to the `return_replynumber` setting value.

We have temporarily solved this by commenting out the entire sanitize function on lines `360-366` and `370-376` of `src/Rest_API/Shipping/Item_Info.php`.
https://github.com/Progressus-io/postnl-for-woocommerce/blob/eb113a212b9e514c5580057f448975c8191903e2/src/Rest_API/Shipping/Item_Info.php#L358-L377

A more robust fix is needed to allow using a normal address for Dutch return labels, as is already possible for Belgian returns. Some logic is probably required to detect whether a reply number or normal address is being used.

**Comment by JorisPostNL** [comment]
Hi Stijn,

Thank you kindly for bringing this to our attention. The option to send returns to a home address in The Netherlands rather than a business reply number  is a relatively new one, and by chance this is already on our roadmap to develop for our plug-ins in the near future. So a more robust fix is definitely on the way, including relevant interface changes and new configuration options.

We are currently finishing work on a complex change in the plug-in and hope to be able to start work on Return to Home Address soon - our aim is to have this released at the end of Q1 or beginning of Q2.

Kind regards,

Joris
Technical Channel Manager - Team Channel Integrations
PostNL

**Comment by stijneikelboom** [comment]
Hi Joris,

Thanks for the update!

Happy to hear support for returns to home addresses is scheduled to be realised. We have communicated your planning (late Q1 until early Q2) to our customer. For now, they will rely on our temporary solution.

Please keep us updated if there are any developments, so we can inform our customer accordingly. Thanks in advance!

Kind regards,
Stijn

**Comment by JorisPostNL** [comment]
Hi @stijneikelboom, a quick update is in order since we're nearing the term within we said we would release Return to Home Address. Unfortunately we did not manage to finish it in Q1 and early Q2 now seems less likely too. We still aim to release this in Q2 though, but mid/late rather than early Q2. We apologise for any inconvenience this may have caused and hope to be able to release the feature asap

Kind regards
Joris

**Comment by JorisPostNL** [comment]
Hi @stijneikelboom just to let you know: we are currently starting testing for the return to home address feature. Since we're in early testing we cannot give an estimate of when they will be deployed, but we hope to be able to release soon.

Kind regards
Joris

**Comment by JorisPostNL** [comment]
Hi @stijneikelboom, it took a little longer than projected, but we are happy to announce that we released a new version of the plug-in which allows for returns to home address. If there are any further issues or requests please don't hestitate to contact us here or at https://developer.postnl.nl/support/form/

Kind regards,
Joris - PostNL

**Comment by stijneikelboom** [comment]
Thank you for the update @JorisPostNL! We have implemented the latest version for our customer and are now awaiting their experiences.
